language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-head
  - ree
  - rbx

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx

sudo: false

bundler_args: "--standalone --binstubs --without documentation"

script:
  - gem install bundler
  - "script/test_all"

notifications:
  email: false
